#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path


RUN_PATTERN = re.compile(r"rec_clas_(\d+)")


def run_number(path: Path) -> int | None:
    match = RUN_PATTERN.search(path.name)
    return int(match.group(1)) if match else None


def evenly_spaced(items: list[Path], count: int) -> list[Path]:
    if count >= len(items):
        return list(items)
    if count == 1:
        return [items[len(items) // 2]]
    indices = [round(index * (len(items) - 1) / (count - 1)) for index in range(count)]
    return [items[index] for index in indices]


def select_sample(
    input_directory: Path,
    *,
    files_per_run: int,
    run_min: int | None = None,
    run_max: int | None = None,
    max_runs: int | None = None,
) -> dict[int, list[Path]]:
    if files_per_run < 1:
        raise ValueError("files per run must be positive")
    by_run: dict[int, list[Path]] = defaultdict(list)
    for path in input_directory.rglob("*.hipo"):
        run = run_number(path)
        if run is None:
            continue
        if run_min is not None and run < run_min:
            continue
        if run_max is not None and run > run_max:
            continue
        by_run[run].append(path.resolve())
    runs = sorted(by_run)
    if max_runs is not None:
        if max_runs < 2:
            raise ValueError("maximum runs must be at least two")
        if max_runs < len(runs):
            indices = [
                round(index * (len(runs) - 1) / (max_runs - 1))
                for index in range(max_runs)
            ]
            runs = [runs[index] for index in indices]
    return {
        run: evenly_spaced(sorted(by_run[run]), files_per_run)
        for run in runs
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Select deterministic, evenly spaced HIPO files within each run and "
            "write a manifest accepted by hipo2root as @manifest."
        )
    )
    parser.add_argument("input_directory", type=Path)
    parser.add_argument("output_manifest", type=Path)
    parser.add_argument("--files-per-run", type=int, default=1)
    parser.add_argument("--run-min", type=int)
    parser.add_argument("--run-max", type=int)
    parser.add_argument("--max-runs", type=int)
    parser.add_argument("--overwrite", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if not args.input_directory.is_dir():
        raise FileNotFoundError(f"input directory does not exist: {args.input_directory}")
    if args.output_manifest.exists() and not args.overwrite:
        raise FileExistsError(
            f"output manifest already exists: {args.output_manifest}; use --overwrite"
        )
    selected = select_sample(
        args.input_directory,
        files_per_run=args.files_per_run,
        run_min=args.run_min,
        run_max=args.run_max,
        max_runs=args.max_runs,
    )
    if not selected:
        raise ValueError("no HIPO files with rec_clas_RUN filenames were found")
    args.output_manifest.parent.mkdir(parents=True, exist_ok=True)
    with args.output_manifest.open("w") as output:
        output.write("# One absolute HIPO path per line; generated by select_hipo_run_sample.py\n")
        for run in sorted(selected):
            for path in selected[run]:
                output.write(f"{path}\n")
    file_count = sum(len(paths) for paths in selected.values())
    print(
        f"Wrote {file_count} files spanning {len(selected)} runs "
        f"({min(selected)}-{max(selected)}) to {args.output_manifest}"
    )


if __name__ == "__main__":
    main()
